### ISSUE TITLE
Service Registration is failing for st2 authentication

### ISSUE THREAD

**Issue by himanshuvar** [opensds/orchestration#72]
**This a BUG REPORT **:

> /kind bug

**What happened**: Service Registration is failing due to st2 authenticate failure

**What you expected to happen**: Service Registration should be successful

**How to reproduce it (as minimally and precisely as possible)**:
Create an Opensds setup for RC2 v0.5.4 release

**Anything else we need to know?**:

**Environment**:
- Orchestration(release/branch) version: v0.5.4
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Logs**
`[2019-06-14 02:05:49,661] [ERROR] [app.py] [log_exception():1780] [PID:57430 TID:139864340199168] Exception on /v1beta/cf04d7c15d294e178597370ccd81498f/orchestration/services [POST]
Traceback (most recent call last):
 File "/opt/orchestration-linux-amd64/venv/local/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
   response = self.full_dispatch_request()
 File "/opt/orchestration-linux-amd64/venv/local/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/opt/orchestration-linux-amd64/venv/local/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/opt/orchestration-linux-amd64/venv/local/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
   rv = self.dispatch_request()
 File "/opt/orchestration-linux-amd64/venv/local/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "build/bdist.linux-x86_64/egg/orchestration/api/services.py", line 121, in add_services
   workflow_definition = get_wfd(def_source_id)
 File "build/bdist.linux-x86_64/egg/orchestration/api/instances.py", line 185, in get_wfd
   rc, ret = c.get_action(id, 'opensds')
 File "build/bdist.linux-x86_64/egg/orchestration/connectionmanager/st2.py", line 69, in get_action
   auth_token = self.authenticate()
 File "build/bdist.linux-x86_64/egg/orchestration/connectionmanager/st2.py", line 39, in authenticate
   return response['token']
KeyError: 'token'`

**Comment by kumarashit** [comment]
Issue is because the orchestration.conf doesn't have correct Orchestration Manager i.e. st2 password set. Once it is set, it will work fine. @joseph-v has already raised a PR to fix it in installer. So this issue can be closed.

**Comment by kumarashit** [comment]
This is issue is already fixed. @skdwriting @wisererik @satya-gorli Please close this

**Comment by kumarashit** [comment]
This was fixed under issue #196 of Opensds-installer

**Comment by skdwriting** [comment]
Closing.
